columns:
- Age: int64
- Sex: string
- ChestPainType: string
- RestingBP: int64
- Cholesterol: int64
- FastingBS: int64
- RestingECG: string
- MaxHR: int64
- ExerciseAngina: string
- Oldpeak: float64
- ST_Slope: string
- HeartDisease: int64
numerical_columns:
- Age
- RestingBP
- Cholesterol
- FastingBS
- MaxHR
- Oldpeak
- HeartDisease
categorical_columns:
- Sex
- ChestPainType
- RestingECG
- ExerciseAngina
- ST_Slope
